config/routes.rb
Rails.application.routes.draw do
  get 'home/top', to: 'home#top'
  root to: 'articles#index'
  devise_for :users
  get 'users/:user_id/avatar/edit', to: 'avatars#edit'
  put 'users/:user_id/avatar', to: 'avatars#update'
  delete 'users/:user_id/avatar', to: 'avatars#destroy'
  resources :users, only: [:show] do
    resources :articles do
      resources :paragraphs, only: [:new, :create, :edit, :update, :destroy] do
        resources :images, only: [:new, :create, :edit, :update, :destroy]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :paragraphs, dependent: :destroy

  validates :title, :summary, presence: true
  validates :user_id, presence: {message: 'を新規登録してください'}
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
  validates :avatar, presence: {message: 'をアップロードしてください'}
  validates :user_id, presence: {message: 'を新規登録してください'}
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :paragraph
  has_one_attached :image
  validates :image, presence: {message: 'をアップロードしてください'}
  validates :paragraph_id, presence: {message: 'を作成してください'}
end

app/models/paragraph.rb
class Paragraph < ApplicationRecord
  belongs_to :article
  has_many :images, dependent: :destroy
  validates :article_id, presence: {message: 'を作成してください'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :avatar, dependent: :destroy
  has_many :articles, dependent: :destroy
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :find_paragraphs, only: [:show, :edit, :destroy]
  before_action :find_current_user, only: [:index, :new, :create, :edit, :update]
  before_action :move_to_show, only: [:edit, :update, :destroy]

  def index
    @articles = Article.order("updated_at DESC")
  end

  def show
    @user = User.find(params[:user_id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "記事が保存されました。"
      redirect_to edit_user_article_path(@user, @article)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "記事が更新されました。"
      redirect_to edit_user_article_path(@user, @article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
  end

  private

  def find_current_user
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def find_paragraphs
    @paragraphs = @article.paragraphs.order("created_at ASC")
  end

  def article_params
    params.require(:article).permit(:title, :summary).merge(user_id: current_user.id)
  end

  def move_to_show
    return unless current_user.id != params[:user_id].to_i
    redirect_to user_article_path(params[:user_id], params[:id])
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_show
  before_action :find_user_avatar

  def edit
  end

  def update
    if @user.avatar == nil
      @avatar = Avatar.new(avatar_params)
      if @avatar.save
        redirect_to user_path(@user)
      else
        flash[:notice] = "画像を選択してください。"
        redirect_to "/users/#{params[:user_id]}/avatar/edit"
      end
    else
      if @avatar.update(avatar_params)
        redirect_to user_path(@user)
      else
        flash[:notice] = "画像を選択してください。"
        redirect_to "/users/#{params[:user_id]}/avatar/edit"
      end
    end
  end

  def destroy
    unless @user.avatar == nil
      @user.avatar.destroy
    end
    redirect_to user_path(@user)
  end

  private

  def find_user_avatar
    @user = User.find(params[:user_id])
    @user.avatar == nil ? @avatar = Avatar.new : @avatar = Avatar.find(@user.avatar.id)
  end

  def avatar_params
    params.permit(:avatar, :user_id)
  end

  def move_to_show
    return if params[:user_id].to_i == current_user.id
    redirect_to "/users/#{params[:user_id]}"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      redirect_to root_path
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_parents
  before_action :move_to_show
  before_action :find_image, only: [:edit, :update, :destroy]
  before_action :image_params, only: [:create, :update]

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:notice] = "画像を保存しました。"
      redirect_to edit_user_article_paragraph_path(@user, @article, @paragraph)
    else
      flash[:notice] = "画像を選択してください。"
      render :new
    end
  end

  def edit
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      flash[:notice] = "画像を更新しました。"
      redirect_to edit_user_article_paragraph_path(@user, @article, @paragraph)
    else
      flash[:notice] = "画像を選択してください。"
      render :edit
    end
  end

  def destroy
    @image.destroy
    flash[:notice] = "画像を削除しました。"
    redirect_to edit_user_article_paragraph_path(@user, @article, @paragraph)
  end

  private

  def find_parents
    @user = User.find(params[:user_id])
    @article = Article.find(params[:article_id])
    @paragraph = Paragraph.find(params[:paragraph_id])
  end

  def find_image
    @image = Image.find(params[:id])
  end

  def move_to_show
    return unless current_user.id != params[:user_id].to_i
    redirect_to user_article_path(params[:user_id], params[:article_id])
  end

  def image_params
    params.permit(:image, :image_explanation, :paragraph_id)
  end
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user_article
  before_action :find_paragraph_images, only: [:edit, :update, :destroy]
  before_action :move_to_show

  def new
    @paragraph = Paragraph.new
  end

  def create
    @paragraph = Paragraph.new(paragraph_params)
    if @paragraph.save
      flash[:notice] = "段落が保存されました。"
      redirect_to edit_user_article_path(@user, @article)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @paragraph.update(paragraph_params)
      flash[:notice] = "段落が更新されました。"
      redirect_to edit_user_article_path(@user, @article)
    else
      render :edit
    end
  end

  def destroy
    @paragraph.destroy
    flash[:notice] = "段落を削除しました。"
    redirect_to edit_user_article_path(@user, @article)
  end

  private

  def find_user_article
    @user = params[:user_id]
    @article = params[:article_id]
  end

  def find_paragraph_images
    @paragraph = Paragraph.find(params[:id])
    @images = @paragraph.images
  end

  def paragraph_params
    params.permit(:headline, :content, :article_id)
  end

  def move_to_show
    return unless current_user.id != params[:user_id].to_i
    redirect_to user_article_path(params[:user_id], params[:article_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.order("updated_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/paragraphs_helper.rb
module ParagraphsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_paragraph.html.erb
<div class="paragraph-hard-code" id="<%= paragraph.id %>">
  <div class="flex">
    <div class="hard-code-headline">
      <%= safe_join(paragraph.headline.split("\n"),tag.br) %>
    </div>
    <% if user_signed_in? && current_user.id == @user.id %>
      <%= link_to edit_user_article_paragraph_path(@user, @article, paragraph), class:"edit-btn" do %>
        <%= image_tag "edit.svg", alt: "編集"%>
      <% end %>
      <%= link_to user_article_paragraph_path(@user, @article, paragraph), class: "trash-btn", method: :delete do %>
        <%= image_tag "trash.svg", alt: "削除" %>
      <% end %>
    <% end %>
  </div>
  <div class="hard-code-content">
    <%= safe_join(paragraph.content.split("\n"),tag.br) %>
  </div>
  <div class="hard-code-images">
    <%= render partial: "paragraphs/image", collection: paragraph.images %>
  </div>
</div>
<!-- //paragraph-hard-code -->

app/views/articles/destroy.html.erb
<%= render partial: "shared/header" %>
<%= render partial: "shared/destroy_message", locals: { message: "記事を削除しました。" } %>
<%= render partial: "shared/footer" %>

app/views/articles/edit.html.erb
<%= render partial: "shared/header" %>
<div class="wrapper">
  <div class="main">
  
    <div><%= flash[:notice] %></div>
    <h2>記事を編集</h2>
    <div class="flex">
      <h3 id="edit-outline">記事のアウトラインを編集</h3>
      <label class="edit-btn" id="edit-outline-btn">
        <%= image_tag "edit.svg", alt: "編集"%>
      </label>
      <label class="trash-btn" id="trash-btn">
        <%= image_tag "trash.svg", alt: "削除" %>
      </label>
      <div class="pop-up" id="pop-up">
        <div class="pop-up-main">
          <div class="pop-up-message">記事を削除しますか？</div>
          <div class="pop-up-flex">
            <div class="cancel-btn">
              <%= link_to "キャンセル", edit_user_article_path(@user, @article) %>
            </div>
            <div class="ok-btn">
              <%= link_to "OK", user_article_path(@user, @article), method: :delete %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%= form_with model: [@user, @article], id: "edit-article-form", local: true do |f| %>
      <%= render "shared/error_messages", model: f.object %>
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title %>
      <%= f.label :summary, "サマリー" %>
      <%= f.text_area :summary %>
      <div class="under-form-btn">
        <div class="cancel-btn">
          <%= link_to "キャンセル", user_article_path(@user, @article) %>
        </div>
        <div class="reset-btn">
          <%= link_to "リセット", edit_user_article_path(@user, @article) %>
        </div>
        <%= f.submit "保存", class: "save-btn", id: "edit-submit-btn" %>
      </div>
    <% end %>
    <!-- //edit-article-form -->

    <div class="paragraphs">

      <%= render partial: "paragraph", collection: @paragraphs %>

      <div id="add-paragraph-bar">
        <div id="paragraph-bar"></div>
        <%= link_to "段落を追加", new_user_article_paragraph_path(@user, @article), class:"save-btn", id: "add-paragraph-btn" %>
      </div>
      <!-- //add-paragraph-bar -->

    </div>
    <!-- //paragraphs -->
    <%= link_to "戻る", user_article_path(@user, @article), id: "return"%>
  
  </div>
  <!-- //main -->
  <div class="side">
    <%= link_to "記事のアウトラインを編集", "#edit-outline", class: "bold" %><%= tag.br %>
    <% unless @paragraphs == nil %>
      <% @paragraphs.each do |paragraph| %>
        <%= link_to paragraph.headline, "##{paragraph.id}" %><%= tag.br %>
      <% end %>
    <% end %>
    <%= link_to "段落を追加", "#add-paragraph-btn" %>
  </div>
  <!-- //side -->
</div>
<!-- //wrapper -->
<%= render partial: "shared/footer" %>

app/views/articles/index.html.erb
<% if user_signed_in? %>
  <%= render partial: "shared/header" %>
<% else %>
  <%= render partial: "shared/second_header" %>
<% end %>
<div class="wrapper">
  <div class="main">
    <div><%= flash[:notice] %></div>
    <div class="articles">
      <%= render partial: "shared/article", collection: @articles %>
    </div>
    <%# 記事一覧 %>
  </div>
  <!-- //main -->
  <div class="side"></div>
  <!-- //side -->
</div>
<!-- //wrapper -->
<%= render partial: "shared/footer" %>

app/views/articles/new.html.erb
<%= render partial: "shared/header" %>
<div class="wrapper">
  <div class="main">
    <div><%= flash[:notice] %></div>
    <h2>記事のアウトラインを作成</h2>
    <%= form_with model: [@user,@article], class: "article-form", local: true do |f| %>
      <%= render "shared/error_messages", model: f.object %>
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title %>
      <%= f.label :summary, "サマリー" %>
      <%= f.text_area :summary %>
      <div class="under-form-btn">
        <div class="cancel-btn">
          <%= link_to "キャンセル", root_path %>
        </div>
        <div class="reset-btn">
          <%= link_to "リセット", new_user_article_path(@user) %>
        </div>
        <%= f.submit "保存", class: "save-btn" %>
      </div>
    <% end %>
  </div>
  <!-- //main -->
  <div class="side">

  </div>
  <!-- //side -->
</div>
<!-- //wrapper -->
<%= render partial: "shared/footer" %>

app/views/avatars/edit.html.erb
<%= render "shared/header" %>
<div class="wrapper">
  <div class="wrapper-content">
    <div><%= flash[:notice] %></div>
    <div class="avatar-edit">
      <% if @user.avatar == nil %>
        <%= image_tag "user.svg" %>
      <% else %>
        <%= image_tag @avatar.avatar %>
      <% end %>
      <div class="avatar-edit-circle"></div>
    </div>
    <%= form_with url: "/users/#{@user.id}/avatar", id: "edit-avatar-form", multipart: true, method: :put, local: true do |f| %>
      <div class="edit-avatar-flex">
        <div>
          <%= f.label :avatar, "画像を変更" %>
          <%= f.file_field :avatar %>
        </div>
        <div>
          [ <%= link_to "画像を削除", "/users/#{@user.id}/avatar", method: :delete %> ]
        </div>
      </div>
      <div class="under-form-btn">
        <div class="cancel-btn">
          <%= link_to "キャンセル", user_path(@user) %>
        </div>
        <div class="reset-btn">
          <%= link_to "リセット", "/users/#{@user.id}/avatar/edit" %>
        </div>
        <%= f.submit "保存", class: "save-btn", id: "edit-submit-btn" %>
      </div>
    <% end %>
  </div>
  <!-- //wrapper-content -->
</div>
<!-- //wrapper -->
<%= render "shared/footer" %>

app/views/images/edit.heml.erb
<%= render partial: "shared/header" %>
<div class="wrapper">
  <div class="main">
    <div><%= flash[:notice] %></div>
    <h2>画像を編集</h2>
    
    <div class="hard-code-image">
      <%= image_tag "/image/#{@image.id}.png" %>
      <div class="hard-code-image-exp">
        <%= @image.image_explanation %>
      </div>
    </div>
    <!-- //hard-code-image -->

    <%= form_with url: user_article_paragraph_images_path(@user, @article, @paragraph, @image), id: "edit-image-form", multipart: true, local: true do |f| %>
      <%= f.label :image, "画像を変更", class: "attach-image-label" %>
      <%= f.file_field :image, class: "attach-image" %>
      <%= f.label :iamge_exp, "画像の説明" %>
      <%= f.text_field :image_exp, id: "edit-image-exp" %>

      <div class="under-paragraph-form-btn">
        <div class="cancel-btn">
          <%= link_to "キャンセル", edit_user_article_paragraph_path(@user, @article, @paragraph) %>
        </div>
        <div class="reset-btn">
          <%= link_to "リセット", edit_user_article_paragraph_image_path(@user, @article, @paragraph) %>
        </div>
        <%= f.submit "保存", class: "save-btn", id: "edit-submit-btn" %>
      </div>
      
    <% end %>
    <!-- //edit-image-form -->

  </div>
  <!-- //main -->
  <div class="side">

  </div>
  <!-- //side -->
</div>
<!-- //wrapper -->
<%= render partial: "shared/footer" %>

app/views/images/edit.html.erb
<%= render partial: "shared/header" %>
<div class="wrapper">
  <div class="main">
    <div><%= flash[:notice] %></div>
    <h2>画像を編集</h2>
    
    <div class="hard-code-image" id="image-preview">
      <%= image_tag @image.image %>
      <div class="hard-code-image-exp" id="image-exp-preview">
        <%= @image.image_explanation %>
      </div>
    </div>
    <!-- //hard-code-image -->

    <%= form_with url: user_article_paragraph_image_path(@user, @article, @paragraph, @image), id: "edit-image-form", method: :patch, multipart: true, local: true do |f| %>
      <%= f.file_field :image, class: "attach-image" %>
      <%= f.label :iamge_explanation, "画像の説明" %>
      <%= f.text_field :image_explanation, id: "edit-image-exp", value: @image.image_explanation %>

      <div class="under-paragraph-form-btn">
        <div class="cancel-btn">
          <%= link_to "キャンセル", edit_user_article_paragraph_path(@user, @article, @paragraph) %>
        </div>
        <div class="reset-btn">
          <%= link_to "リセット", edit_user_article_paragraph_image_path(@user, @article, @paragraph) %>
        </div>
        <%= f.submit "保存", class: "save-btn", id: "edit-submit-btn" %>
      </div>
      
    <% end %>
    <!-- //edit-image-form -->

  </div>
  <!-- //main -->
  <div class="side">

  </div>
  <!-- //side -->
</div>
<!-- //wrapper -->
<%= render partial: "shared/footer" %>

app/views/images/new.html.erb
<%= render partial: "shared/header" %>
<div class="wrapper">
  <div class="main">
    <div><%= flash[:notice] %></div>
    <h2>画像を追加</h2>
      
    <div class="hard-code-image" id="image-preview">
      <div class="hard-code-image-exp" id="image-exp-preview"></div>
    </div>
    <!-- //hard-code-image -->

    <%= form_with url: user_article_paragraph_images_path(@user, @article, @paragraph), id: "edit-image-form", multipart: true, local: true do |f| %>
      <%= f.file_field :image, class: "attach-image" %>
      <%= f.label :iamge_explanation, "画像の説明" %>
      <%= f.text_field :image_explanation, id: "edit-image-exp" %>

      <div class="under-paragraph-form-btn">
        <div class="cancel-btn">
          <%= link_to "キャンセル", edit_user_article_paragraph_path(@user, @article, @paragraph) %>
        </div>
        <div class="reset-btn">
          <%= link_to "リセット", new_user_article_paragraph_image_path(@user, @article, @paragraph) %>
        </div>
        <%= f.submit "保存", class: "save-btn", id: "edit-submit-btn" %>
      </div>
      
    <% end %>
    <!-- //edit-image-form -->

  </div>
  <!-- //main -->
  <div class="side">

  </div>
  <!-- //side -->
</div>
<!-- //wrapper -->
<%= render partial: "shared/footer" %>

app/views/paragraphs/_image.html.erb
<div class="hard-code-image">
  <% if user_signed_in? && current_user.id == image.paragraph.article.user.id %>
    <div class="flex">
      <div>画像を編集</div>
      <%= link_to edit_user_article_paragraph_image_path(image.paragraph.article.user, image.paragraph.article, image.paragraph, image), class: "edit-btn" do %>
        <%= image_tag "edit.svg", alt: "編集" %>
      <% end %>
      <%= link_to user_article_paragraph_image_path(image.paragraph.article.user, image.paragraph.article, image.paragraph, image), class: "trash-btn", method: :delete do %>
        <%= image_tag "trash.svg", alt: "削除" %>
      <% end %>
    </div>
  <% end %>
  <%= image_tag image.image %>
  <div class="hard-code-image-exp">
    <%= image.image_explanation %>
  </div>
</div>
<!-- //hard-code-image -->

app/views/paragraphs/edit.html.erb
<%= render partial: "shared/header" %>
<div class="wrapper">
  <div class="main">
    <div><%= flash[:notice] %></div>
    <div class="flex">
      <h2>段落を編集</h2>
      <label class="edit-btn" id="edit-paragraph-btn">
        <%= image_tag "edit.svg", alt: "編集" %>
      </label>
    </div>

    <%= form_with url: user_article_paragraph_path(@user, @article, @paragraph), id: "edit-paragraph-form", method: :patch, local: true do |f| %>
      <%= f.label :headline, "見出し" %>
      <%= f.text_field :headline, value: @paragraph.headline %>
      <%= f.label :content, "本文" %>
      <%= f.text_area :content, value: @paragraph.content %>

      <div class="under-paragraph-form-btn">
        <div class="cancel-btn">
          <%= link_to "キャンセル", edit_user_article_path(@user, @article) %>
        </div>
        <div class="reset-btn">
          <%= link_to "リセット", edit_user_article_paragraph_path(@user, @article, @paragraph) %>
        </div>
        <%= f.submit "保存", class: "save-btn", id: "edit-submit-btn" %>
      </div>
      
    <% end %>
    <!-- //edit-paragraph-form -->

    <div class="hard-code-images">
      <%= render partial: "image", collection: @images %>
    </div>
    <!-- //hard-code-images -->

    <div id="add-image-bar">
      <div id="image-bar"></div>
      <%= link_to "画像を追加", new_user_article_paragraph_image_path(@user, @article, @paragraph), class: "save-btn", id: "add-image-btn" %>
    </div>
    <!-- //add-image-bar -->
    <%= link_to "戻る", edit_user_article_path(@user, @article), id: "return" %>
  </div>
  <!-- //main -->
  <div class="side">
  </div>
  <!-- //side -->
</div>
<!-- //wrapper -->
<%= render partial: "shared/footer" %>

app/views/paragraphs/new.html.erb
<%= render partial: "shared/header" %>
<div class="wrapper">
  <div class="main">
    <div><%= flash[:notice] %></div>
    <h2>段落を作成</h2>
    <%= form_with url: user_article_paragraphs_path(@user, @article, @paragraph), class: "paragraph-form", local: true do |f| %>
      <%= f.label :headline, "見出し" %>
      <%= f.text_field :headline %>
      <%= f.label :content, "本文" %>
      <%= f.text_area :content %>
      <div class="under-form-btn">
        <div class="cancel-btn">
          <%= link_to "キャンセル", edit_user_article_path(@user, @article) %>
        </div>
        <div class="reset-btn">
          <%= link_to "リセット", new_user_article_paragraph_path(@user, @article) %>
        </div>
        <%= f.submit "保存", class: "save-btn" %>
      </div>
    <% end %>
  </div>
  <!-- //main -->
  <div class="side">

  </div>
  <!-- //side -->
</div>
<!-- //wrapper -->
<%= render partial: "shared/footer" %>

app/views/shared/_header.html.erb
<header>
  <div class="content header-content">
    <div class="header-logo-wrap">
      <div class="header-logo">
        <%= link_to "Life Master", root_path %>
      </div>
      <div class="sub-logo">生活を豊かにするアイデア投稿サイト</div>
    </div>
    <div class="header-menu">
      <div>
        <label class="header-menu-open" id="menu-open">
          <div></div>
          <div></div>
          <div></div>
        </label>
        <div class="header-menu-items" id="menu-items">
          <%= link_to user_path(current_user), style: "width:auto" do %>
            <div id="header-user-name">
              <%= current_user.name %>
            </div>
          <% end %>
          <%= link_to root_path do %>
            <div class="header-menu-image">
              <%= image_tag "articles.svg" %>
            </div>
            記事一覧
          <% end %>
          
          <%= link_to new_user_article_path(current_user) do %>
            <div class="header-menu-image">
              <%= image_tag "new-black.svg" %>
            </div>
            新規作成
          <% end %>
          
          <%= link_to user_path(current_user) do %>
            <div class="header-menu-image">
              <%= image_tag "user.svg" %>
            </div>
            マイページ
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <div class="header-menu-image">
              <%= image_tag "logout.svg" %>
            </div>
            ログアウト
          <% end %>
        </div>
        <label class="header-menu-close" id="menu-close">
          <div></div>
          <div></div>
        </label>
      </div>
    </div>
  </div>
</header>

app/views/shared/_second_header.html.erb
<header>
  <div class="content header-content">
    <div class="header-logo-wrap">
      <div class="header-logo">
        <%= link_to "Life Master", home_top_path %>
      </div>
      <div class="sub-logo">生活を豊かにするアイデア投稿サイト</div>
    </div>
    <div class="header-menu">
      <div>
        <label class="header-menu-open" id="menu-open">
          <div></div>
          <div></div>
          <div></div>
        </label>
        <div class="header-menu-items" id="menu-items">
          <%= link_to root_path do %>
            <div class="header-menu-image">
              <%= image_tag "articles.svg" %>
            </div>
            記事一覧
          <% end %>
          
          <%= link_to new_user_session_path do %>
            <div class="header-menu-image">
              <%= image_tag "login.svg" %>
            </div>
            ログイン
          <%  end %>
          
          <%= link_to new_user_registration_path do %>
            <div class="header-menu-image">
              <%= image_tag "user-new.svg" %>
            </div>
            新規登録
          <% end %>
          
        </div>
        <label class="header-menu-close" id="menu-close">
          <div></div>
          <div></div>
        </label>
      </div>
    </div>
  </div>
</header>

app/views/users/show.html.erb
<%= render partial: "shared/header" %>
<div class="wrapper">
  <div class="main">
    <div class="user-info">
      <div class="mypage-avatar">
        <div class="mypage-avatar-inner">
          <% if @user.avatar == nil %>
            <%= image_tag "user.svg" %>
          <% else %>
            <%= image_tag @user.avatar.avatar %>
          <% end %>
        </div>
        <% if user_signed_in? && current_user.id == @user.id %>
          <%= link_to "/users/#{@user.id}/avatar/edit", class: "edit-btn", id: "mypage-avatar-edit" do %>
            <%= image_tag "edit.svg", alt: "編集" %>
          <% end %>
        <% end %>
      </div>
      <div class="mypage-name">
        <%= @user.name %>
      </div>
      <% if user_signed_in? && current_user.id == @user.id %>
        <div class="mypage-edit-or-delete">
          <div>
            [ <%= link_to "アカウント編集", edit_registration_path(@user) %> ]
          </div>
          <div>
            [ <span id="trash-btn">アカウント削除</span> ]
          </div>
        </div>
        <div class="pop-up" id="pop-up">
          <div class="pop-up-main">
            <div class="pop-up-message">アカウントを削除しますか？</div>
            <div class="pop-up-flex">
              <div class="cancel-btn">
                <%= link_to "キャンセル", user_path(@user) %>
              </div>
              <div class="ok-btn">
                <%= link_to "OK", registration_path(@user), method: :delete %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <!-- 記事一覧 -->
    <div class="articles">
      <%= render partial: "shared/article", collection: @articles %>
    </div>
    <!-- //記事一覧 -->
  </div>
  <!-- //main -->
  <div class="side">

  </div>
  <!-- //side -->
</div>
<!-- //wrapper -->
<%= render partial: "shared/footer" %>